development:
    dialect: mysql
    datasource: fooddelivery:P@ssw0rd@tcp(35.240.188.29:3306)/fooddelivery?charset=utf8mb4&parseTime=True
    dir: migrations
    table: migrations

production:
    dialect: mysql
    datasource: ${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${DATABASE_NAME}?charset=utf8mb4&parseTime=True
    dir: migrations
    table: migrations